name: Promote to Dev
on:
  push:
    branches:
      - master
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
jobs:
  tag:
    name: Tag Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Tag Master Branch
      run: 'echo Insert work here.'
  validate:
    name: Deploy and Validate Against Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Write the token into a file
        run: 'echo ${{secrets.CUMULUS_DEV_AUTH}} > auth.txt'
      - name: Auth with Dev
        run: 'sfdx force:auth:sfdxurl:store -f auth.txt -a dev -d'
      - name: Import Org into CCI
        run: 'cci org import dev dev'
      - name: Deploy to Dev
        run: |
          cci flow run dependencies --org dev
          cci flow run deploy_unmanaged --org dev
      - name: Run Unit Tests
        run: 'cci task run run_tests --org dev'
      - name: Run Robot Tests
        run: 'cci task run robot --org dev -o vars BROWSER:headlesschrome'
      - name: Back Merge to Feature Branches
        run: 'cci task run github_automerge_main'
  sanity:
    name: Run Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Install sfdx Scanner Plugin
        run: "sfdx plugins:install @salesforce/sfdx-scanner"
      - name: Code Scan
        run: 'sfdx scanner:run -t ./force-app/ --pmdconfig ./config/pmd/apex_ruleset.xml -s 3'