name: Promote to Int
on:
  push:
    branches:
      - master
env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
jobs:
  tag:
    name: Tag Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Tag Master Branch
      run: 'echo Insert work here.'
  validate:
    name: Deploy and Validate Against Int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Write the token into a file
        run: 'echo ${{secrets.INT_TOKEN}} > auth.txt'
      - name: Auth with Int
        run: 'sfdx force:auth:sfdxurl:store -f auth.txt -a int -d'
      - name: Import Org into CCI
        run: 'cci org import int int'
      - name: Deploy to int
        run: |
          cci flow run dependencies --org int
          cci flow run deploy_unmanaged --org int
      - name: Run Unit Tests
        run: 'cci task run run_tests --org int'
      - name: Run Robot Tests
        run: 'cci task run robot --org int -o vars BROWSER:headlesschrome'
      - name: Back Merge to Feature Branches
        run: 'cci task run github_automerge_main'
  sanity:
    name: Run Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install sfdx
        run: "npm install sfdx-cli --global"
      - name: Install sfdx Scanner Plugin
        run: "sfdx plugins:install @salesforce/sfdx-scanner"
      - name: Code Scan (FORCE PASS)
        run: |
          echo Set to force pass. To enable gated checks, add -s 3.
          sfdx scanner:run -t ./force-app/ --pmdconfig ./config/pmd/apex_ruleset.xml