# .github/workflows/example-1.yml

name: Promote Beta to Released
on: [ workflow_dispatch ]
jobs:
  example:
    name: "Promote Beta"
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          pip install cumulusci
      - name: Create Beta Package Version
        run: |
          cci flow run release_unlocked_production --org release
      - name: Run Robot Tests
        run: |
          cci task run robot --org release -o vars BROWSER:headlesschrome
      - name: Store robot results
        uses: actions/upload-artifact@v1
        with:
          name: robot
          path: robot/fflib-apex-mocks/results
